export const errors = {
  THEME: 'THEME ERROR',
  THEME_SCHEMA: 'THEME SCHEMA ERROR',
  PROJECT: 'PROJECT DATA ERROR',
  DATA_ACCESS: 'DATA ACCESS ERROR',
  PARCEL: 'CSS, JAVASCRIPT or ASSETS ERROR',
  PARCEL_BUILD_UNDEFINED: 'PARCEL BUILD UNDEFINED ERROR',
  STATIC: 'STATIC HTML BUILD ERROR'
}
