export const errors = {
  DATA_ACCESS: 'DATA ACCESS ERROR',
  PARCEL: 'CSS, JAVASCRIPT or ASSETS ERROR',
  PARCEL_BUILD_UNDEFINED: 'PARCEL BUILD UNDEFINED ERROR',
  STATIC: 'STATIC HTML BUILD ERROR',
  THEME: 'THEME ERROR'
}
